// SECTION-MENU categories (docs/SECTION-MENU.md). Each category has its own lab page: /lab/sections/<slug>.
// The layouts of a category live in components/sections/<file>.tsx files, gathered in components/sections/cat/<slug>.tsx.
export type Cat = { slug: string; code: string; name: string };
export const CATS: Cat[] = [
  { slug: "hr", code: "HR", name: "Hero" },
  { slug: "nv", code: "NV", name: "Navbar / menu" },
  { slug: "ft", code: "FT", name: "Features" },
  { slug: "bn", code: "BN", name: "Bento" },
  { slug: "ps", code: "PS", name: "Product showcase" },
  { slug: "st", code: "ST", name: "Stats / ingredients" },
  { slug: "pd", code: "PD", name: "Process / steps" },
  { slug: "cp", code: "CP", name: "Comparison / before-after" },
  { slug: "sy", code: "SY", name: "Story / about" },
  { slug: "tm", code: "TM", name: "Team" },
  { slug: "gl", code: "GL", name: "Gallery" },
  { slug: "vd", code: "VD", name: "Video feature" },
  { slug: "sp", code: "SP", name: "Social proof" },
  { slug: "lg", code: "LG", name: "Logos / press" },
  { slug: "pr", code: "PR", name: "Pricing / shop" },
  { slug: "mn", code: "MN", name: "Menu / price list" },
  { slug: "bk", code: "BK", name: "Booking / reservation" },
  { slug: "ls", code: "LS", name: "Listings / rooms / property" },
  { slug: "mp", code: "MP", name: "Locations / map" },
  { slug: "ev", code: "EV", name: "Events / schedule" },
  { slug: "ap", code: "AP", name: "App download" },
  { slug: "jr", code: "JR", name: "Journal / blog" },
  { slug: "fq", code: "FQ", name: "FAQ" },
  { slug: "ct", code: "CT", name: "CTA band" },
  { slug: "nl", code: "NL", name: "Newsletter" },
  { slug: "cc", code: "CC", name: "Contact" },
  { slug: "fo", code: "FO", name: "Footer" },
  { slug: "an", code: "AN", name: "Announcement / promo bar" },
  { slug: "pl", code: "PL", name: "Poll / vote" },
  { slug: "cr", code: "CR", name: "Careers" },
  { slug: "er", code: "ER", name: "Error / 404" },
];
