// Motion batch pages that exist (/lab/motion/b<N>). Generated by scripts/motion-cats.mjs — do not edit.
export const MBATCHES: number[] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19];
