"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";
import LabShell from "./LabShell";

// One chunk per category, so each /lab/sections/<slug> page loads only its own layouts (rendered on the server too).
// Generated by scripts/section-cats.mjs — do not edit.
const PAGES: Record<string, ComponentType> = {
  hr: dynamic(() => import("@/components/sections/cat/hr").then((m) => function L() { return <LabShell slug="hr" defs={m.DEFS} />; })),
  nv: dynamic(() => import("@/components/sections/cat/nv").then((m) => function L() { return <LabShell slug="nv" defs={m.DEFS} />; })),
  ft: dynamic(() => import("@/components/sections/cat/ft").then((m) => function L() { return <LabShell slug="ft" defs={m.DEFS} />; })),
  bn: dynamic(() => import("@/components/sections/cat/bn").then((m) => function L() { return <LabShell slug="bn" defs={m.DEFS} />; })),
  ps: dynamic(() => import("@/components/sections/cat/ps").then((m) => function L() { return <LabShell slug="ps" defs={m.DEFS} />; })),
  st: dynamic(() => import("@/components/sections/cat/st").then((m) => function L() { return <LabShell slug="st" defs={m.DEFS} />; })),
  pd: dynamic(() => import("@/components/sections/cat/pd").then((m) => function L() { return <LabShell slug="pd" defs={m.DEFS} />; })),
  cp: dynamic(() => import("@/components/sections/cat/cp").then((m) => function L() { return <LabShell slug="cp" defs={m.DEFS} />; })),
  sy: dynamic(() => import("@/components/sections/cat/sy").then((m) => function L() { return <LabShell slug="sy" defs={m.DEFS} />; })),
  tm: dynamic(() => import("@/components/sections/cat/tm").then((m) => function L() { return <LabShell slug="tm" defs={m.DEFS} />; })),
  gl: dynamic(() => import("@/components/sections/cat/gl").then((m) => function L() { return <LabShell slug="gl" defs={m.DEFS} />; })),
  vd: dynamic(() => import("@/components/sections/cat/vd").then((m) => function L() { return <LabShell slug="vd" defs={m.DEFS} />; })),
  sp: dynamic(() => import("@/components/sections/cat/sp").then((m) => function L() { return <LabShell slug="sp" defs={m.DEFS} />; })),
  lg: dynamic(() => import("@/components/sections/cat/lg").then((m) => function L() { return <LabShell slug="lg" defs={m.DEFS} />; })),
  pr: dynamic(() => import("@/components/sections/cat/pr").then((m) => function L() { return <LabShell slug="pr" defs={m.DEFS} />; })),
  mn: dynamic(() => import("@/components/sections/cat/mn").then((m) => function L() { return <LabShell slug="mn" defs={m.DEFS} />; })),
  bk: dynamic(() => import("@/components/sections/cat/bk").then((m) => function L() { return <LabShell slug="bk" defs={m.DEFS} />; })),
  ls: dynamic(() => import("@/components/sections/cat/ls").then((m) => function L() { return <LabShell slug="ls" defs={m.DEFS} />; })),
  mp: dynamic(() => import("@/components/sections/cat/mp").then((m) => function L() { return <LabShell slug="mp" defs={m.DEFS} />; })),
  ev: dynamic(() => import("@/components/sections/cat/ev").then((m) => function L() { return <LabShell slug="ev" defs={m.DEFS} />; })),
  ap: dynamic(() => import("@/components/sections/cat/ap").then((m) => function L() { return <LabShell slug="ap" defs={m.DEFS} />; })),
  jr: dynamic(() => import("@/components/sections/cat/jr").then((m) => function L() { return <LabShell slug="jr" defs={m.DEFS} />; })),
  fq: dynamic(() => import("@/components/sections/cat/fq").then((m) => function L() { return <LabShell slug="fq" defs={m.DEFS} />; })),
  ct: dynamic(() => import("@/components/sections/cat/ct").then((m) => function L() { return <LabShell slug="ct" defs={m.DEFS} />; })),
  nl: dynamic(() => import("@/components/sections/cat/nl").then((m) => function L() { return <LabShell slug="nl" defs={m.DEFS} />; })),
  cc: dynamic(() => import("@/components/sections/cat/cc").then((m) => function L() { return <LabShell slug="cc" defs={m.DEFS} />; })),
  fo: dynamic(() => import("@/components/sections/cat/fo").then((m) => function L() { return <LabShell slug="fo" defs={m.DEFS} />; })),
  an: dynamic(() => import("@/components/sections/cat/an").then((m) => function L() { return <LabShell slug="an" defs={m.DEFS} />; })),
  pl: dynamic(() => import("@/components/sections/cat/pl").then((m) => function L() { return <LabShell slug="pl" defs={m.DEFS} />; })),
  cr: dynamic(() => import("@/components/sections/cat/cr").then((m) => function L() { return <LabShell slug="cr" defs={m.DEFS} />; })),
  er: dynamic(() => import("@/components/sections/cat/er").then((m) => function L() { return <LabShell slug="er" defs={m.DEFS} />; })),
  b1: dynamic(() => import("@/components/sections/cat/b1").then((m) => function L() { return <LabShell slug="b1" defs={m.DEFS} />; })),
  b2: dynamic(() => import("@/components/sections/cat/b2").then((m) => function L() { return <LabShell slug="b2" defs={m.DEFS} />; })),
  b3: dynamic(() => import("@/components/sections/cat/b3").then((m) => function L() { return <LabShell slug="b3" defs={m.DEFS} />; })),
};

export default function CategoryLab({ slug }: { slug: string }) {
  const P = PAGES[slug];
  return P ? <P /> : null;
}
