// Regenerates components/motion/cat/<slug>.tsx (all motions of a group, in code order), components/motion/batches.ts and
// app/lab/motion/GroupLab.tsx (one lazily loaded page per group and per build batch) from the files on disk.
// A group's motions = every components/motion/<slug>-b<N>.tsx batch file (export DEFS: MotionDef[]).
//   node scripts/motion-cats.mjs
import { readFileSync, readdirSync, writeFileSync } from "node:fs";

const slugs = [...readFileSync("components/motion/catalog.ts", "utf8").matchAll(/slug: "(\w+)"/g)].map((m) => m[1]);
const files = readdirSync("components/motion");
const num = (c) => parseInt(c.replace(/\D/g, ""), 10);
const write = (path, imports, ids, note) =>
  writeFileSync(
    path,
    `"use client";\n\n// ${note} Generated by scripts/motion-cats.mjs — do not edit.\nimport type { MotionDef } from "../types";\n${imports.join("\n")}${imports.length ? "\n" : ""}\nexport const DEFS: MotionDef[] = ([${ids.map((i) => `...${i}`).join(", ")}] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || ${"parseInt(a.code.slice(1)) - parseInt(b.code.slice(1))"});\n`,
  );
const idOf = (f) => f.replace(".tsx", "").replace(/-/g, "_").toUpperCase();
for (const s of slugs) {
  const fs = files.filter((f) => new RegExp(`^${s}-b\\d+(-\\d+)?\\.tsx$`).test(f)).sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
  write(`components/motion/cat/${s}.tsx`, fs.map((f) => `import { DEFS as ${idOf(f)} } from "../${f.replace(".tsx", "")}";`), fs.map(idOf), `All motions of the "${s}" group, in code order.`);
}
const batchNums = [...new Set(files.map((f) => f.match(/^[a-z]+-b(\d+)(?:-\d+)?\.tsx$/)?.[1]).filter(Boolean))].sort((a, b) => a - b);
for (const n of batchNums) {
  const fs = files.filter((f) => new RegExp(`^[a-z]+-b${n}(-\\d+)?\\.tsx$`).test(f)).sort((a, b) => slugs.indexOf(a.split("-b")[0]) - slugs.indexOf(b.split("-b")[0]));
  write(`components/motion/cat/b${n}.tsx`, fs.map((f) => `import { DEFS as ${idOf(f)} } from "../${f.replace(".tsx", "")}";`), fs.map(idOf), `All motions of batch ${n}.`);
}
writeFileSync("components/motion/batches.ts", `// Motion batch pages that exist (/lab/motion/b<N>). Generated by scripts/motion-cats.mjs — do not edit.\nexport const MBATCHES: number[] = [${batchNums.join(", ")}];\n`);
const pages = [...slugs, ...batchNums.map((n) => `b${n}`)];
writeFileSync(
  "app/lab/motion/GroupLab.tsx",
  `"use client";\n\nimport dynamic from "next/dynamic";\nimport type { ComponentType } from "react";\nimport MotionShell from "./MotionShell";\n\n// One chunk per group / batch page. Generated by scripts/motion-cats.mjs — do not edit.\nconst PAGES: Record<string, ComponentType> = {\n${pages.map((s) => `  ${s}: dynamic(() => import("@/components/motion/cat/${s}").then((m) => function L() { return <MotionShell slug="${s}" defs={m.DEFS} />; })),`).join("\n")}\n};\n\nexport default function GroupLab({ slug }: { slug: string }) {\n  const P = PAGES[slug];\n  return P ? <P /> : null;\n}\n`,
);
console.log(`motion cats: ${slugs.length} groups, batches: ${batchNums.join(" ") || "none"}`);
