// Regenerates components/sections/cat/<slug>.tsx (all layouts of a category, in code order) and
// app/lab/sections/CategoryLab.tsx (one lazily loaded page per category) from catalog.ts + the files on disk.
// A category's layouts = its first-set file (hero.tsx …) + every <slug>-b<N>.tsx batch file (export DEFS).
//   node scripts/section-cats.mjs
import { readFileSync, readdirSync, writeFileSync } from "node:fs";

const FIRST = { hr: ["hero", "HERO"], ft: ["features", "FEATURES"], bn: ["bento", "BENTO"], ps: ["product", "PRODUCT"], st: ["stats", "STATS"], sy: ["story", "STORY"], gl: ["gallery", "GALLERY"], sp: ["proof", "PROOF"], pr: ["pricing", "PRICING"], fq: ["faq", "FAQ"], ct: ["cta", "CTA"], nl: ["newsletter", "NEWSLETTER"], fo: ["footer", "FOOTER"] };
const slugs = [...readFileSync("components/sections/catalog.ts", "utf8").matchAll(/slug: "(\w+)"/g)].map((m) => m[1]);
const files = readdirSync("components/sections");
for (const s of slugs) {
  const imp = [];
  const arr = [];
  if (FIRST[s]) {
    imp.push(`import { ${FIRST[s][1]} } from "../${FIRST[s][0]}";`);
    arr.push(`...${FIRST[s][1]}`);
  }
  const batches = files.filter((f) => new RegExp(`^${s}-b(\\d+)\\.tsx$`).test(f)).sort((a, b) => parseInt(a.split("-b")[1]) - parseInt(b.split("-b")[1]));
  for (const f of batches) {
    const n = f.replace(".tsx", "");
    const id = n.replace("-", "_").toUpperCase();
    imp.push(`import { DEFS as ${id} } from "../${n}";`);
    arr.push(`...${id}`);
  }
  writeFileSync(
    `components/sections/cat/${s}.tsx`,
    `"use client";\n\n// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.\nimport type { SectionDef } from "../types";\n${imp.join("\n")}${imp.length ? "\n" : ""}\nexport const DEFS: SectionDef[] = ([${arr.join(", ")}] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));\n`,
  );
}
// batch pages (/lab/sections/b<N>): every <slug>-b<N>.tsx file of one batch, recorded once per batch
const batchNums = [...new Set(files.map((f) => f.match(/^[a-z]{2}-b(\d+)\.tsx$/)?.[1]).filter(Boolean))].sort((a, b) => a - b);
for (const n of batchNums) {
  const fs = files.filter((f) => new RegExp(`^[a-z]{2}-b${n}\\.tsx$`).test(f)).sort((a, b) => slugs.indexOf(a.slice(0, 2)) - slugs.indexOf(b.slice(0, 2)));
  const ids = fs.map((f) => f.replace(".tsx", "").replace("-", "_").toUpperCase());
  writeFileSync(
    `components/sections/cat/b${n}.tsx`,
    `"use client";\n\n// All layouts of batch ${n} (category order). Generated by scripts/section-cats.mjs — do not edit.\nimport type { SectionDef } from "../types";\n${fs.map((f, i) => `import { DEFS as ${ids[i]} } from "../${f.replace(".tsx", "")}";`).join("\n")}\n\nexport const DEFS: SectionDef[] = [${ids.map((i) => `...${i}`).join(", ")}];\n`,
  );
}
writeFileSync("components/sections/batches.ts", `// Batch pages that exist (/lab/sections/b<N>). Generated by scripts/section-cats.mjs — do not edit.\nexport const BATCHES: number[] = [${batchNums.join(", ")}];\n`);
const pageSlugs = [...slugs, ...batchNums.map((n) => `b${n}`)];
const loaders = pageSlugs.map((s) => `  ${s}: dynamic(() => import("@/components/sections/cat/${s}").then((m) => function L() { return <LabShell slug="${s}" defs={m.DEFS} />; })),`).join("\n");
writeFileSync(
  "app/lab/sections/CategoryLab.tsx",
  `"use client";\n\nimport dynamic from "next/dynamic";\nimport type { ComponentType } from "react";\nimport LabShell from "./LabShell";\n\n// One chunk per category, so each /lab/sections/<slug> page loads only its own layouts (rendered on the server too).\n// Generated by scripts/section-cats.mjs — do not edit.\nconst PAGES: Record<string, ComponentType> = {\n${loaders}\n};\n\nexport default function CategoryLab({ slug }: { slug: string }) {\n  const P = PAGES[slug];\n  return P ? <P /> : null;\n}\n`,
);
console.log(`section cats: ${slugs.length} categories, batches: ${batchNums.join(" ") || "none"}`);
