"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";
import MotionShell from "./MotionShell";

// One chunk per group / batch page. Generated by scripts/motion-cats.mjs — do not edit.
const PAGES: Record<string, ComponentType> = {
  reveal: dynamic(() => import("@/components/motion/cat/reveal").then((m) => function L() { return <MotionShell slug="reveal" defs={m.DEFS} />; })),
  text: dynamic(() => import("@/components/motion/cat/text").then((m) => function L() { return <MotionShell slug="text" defs={m.DEFS} />; })),
  scroll: dynamic(() => import("@/components/motion/cat/scroll").then((m) => function L() { return <MotionShell slug="scroll" defs={m.DEFS} />; })),
  image: dynamic(() => import("@/components/motion/cat/image").then((m) => function L() { return <MotionShell slug="image" defs={m.DEFS} />; })),
  ambient: dynamic(() => import("@/components/motion/cat/ambient").then((m) => function L() { return <MotionShell slug="ambient" defs={m.DEFS} />; })),
  transition: dynamic(() => import("@/components/motion/cat/transition").then((m) => function L() { return <MotionShell slug="transition" defs={m.DEFS} />; })),
  loader: dynamic(() => import("@/components/motion/cat/loader").then((m) => function L() { return <MotionShell slug="loader" defs={m.DEFS} />; })),
  micro: dynamic(() => import("@/components/motion/cat/micro").then((m) => function L() { return <MotionShell slug="micro" defs={m.DEFS} />; })),
  b1: dynamic(() => import("@/components/motion/cat/b1").then((m) => function L() { return <MotionShell slug="b1" defs={m.DEFS} />; })),
  b2: dynamic(() => import("@/components/motion/cat/b2").then((m) => function L() { return <MotionShell slug="b2" defs={m.DEFS} />; })),
};

export default function GroupLab({ slug }: { slug: string }) {
  const P = PAGES[slug];
  return P ? <P /> : null;
}
