"use client";

import dynamic from "next/dynamic";
import type { ComponentType } from "react";
import MotionShell from "./MotionShell";

// One chunk per group / batch page. Generated by scripts/motion-cats.mjs — do not edit.
const PAGES: Record<string, ComponentType> = {
  reveal: dynamic(() => import("@/components/motion/cat/reveal").then((m) => function L() { return <MotionShell slug="reveal" defs={m.DEFS} />; })),
  text: dynamic(() => import("@/components/motion/cat/text").then((m) => function L() { return <MotionShell slug="text" defs={m.DEFS} />; })),
  scroll: dynamic(() => import("@/components/motion/cat/scroll").then((m) => function L() { return <MotionShell slug="scroll" defs={m.DEFS} />; })),
  image: dynamic(() => import("@/components/motion/cat/image").then((m) => function L() { return <MotionShell slug="image" defs={m.DEFS} />; })),
  ambient: dynamic(() => import("@/components/motion/cat/ambient").then((m) => function L() { return <MotionShell slug="ambient" defs={m.DEFS} />; })),
  transition: dynamic(() => import("@/components/motion/cat/transition").then((m) => function L() { return <MotionShell slug="transition" defs={m.DEFS} />; })),
  loader: dynamic(() => import("@/components/motion/cat/loader").then((m) => function L() { return <MotionShell slug="loader" defs={m.DEFS} />; })),
  micro: dynamic(() => import("@/components/motion/cat/micro").then((m) => function L() { return <MotionShell slug="micro" defs={m.DEFS} />; })),
  b1: dynamic(() => import("@/components/motion/cat/b1").then((m) => function L() { return <MotionShell slug="b1" defs={m.DEFS} />; })),
  b2: dynamic(() => import("@/components/motion/cat/b2").then((m) => function L() { return <MotionShell slug="b2" defs={m.DEFS} />; })),
  b3: dynamic(() => import("@/components/motion/cat/b3").then((m) => function L() { return <MotionShell slug="b3" defs={m.DEFS} />; })),
  b4: dynamic(() => import("@/components/motion/cat/b4").then((m) => function L() { return <MotionShell slug="b4" defs={m.DEFS} />; })),
  b5: dynamic(() => import("@/components/motion/cat/b5").then((m) => function L() { return <MotionShell slug="b5" defs={m.DEFS} />; })),
  b6: dynamic(() => import("@/components/motion/cat/b6").then((m) => function L() { return <MotionShell slug="b6" defs={m.DEFS} />; })),
  b7: dynamic(() => import("@/components/motion/cat/b7").then((m) => function L() { return <MotionShell slug="b7" defs={m.DEFS} />; })),
  b8: dynamic(() => import("@/components/motion/cat/b8").then((m) => function L() { return <MotionShell slug="b8" defs={m.DEFS} />; })),
  b9: dynamic(() => import("@/components/motion/cat/b9").then((m) => function L() { return <MotionShell slug="b9" defs={m.DEFS} />; })),
  b10: dynamic(() => import("@/components/motion/cat/b10").then((m) => function L() { return <MotionShell slug="b10" defs={m.DEFS} />; })),
  b11: dynamic(() => import("@/components/motion/cat/b11").then((m) => function L() { return <MotionShell slug="b11" defs={m.DEFS} />; })),
  b12: dynamic(() => import("@/components/motion/cat/b12").then((m) => function L() { return <MotionShell slug="b12" defs={m.DEFS} />; })),
  b13: dynamic(() => import("@/components/motion/cat/b13").then((m) => function L() { return <MotionShell slug="b13" defs={m.DEFS} />; })),
  b1h1: dynamic(() => import("@/components/motion/cat/b1").then((m) => function L() { return <MotionShell slug="b1h1" defs={m.DEFS.slice(0, Math.ceil(m.DEFS.length / 2))} />; })),
  b1h2: dynamic(() => import("@/components/motion/cat/b1").then((m) => function L() { return <MotionShell slug="b1h2" defs={m.DEFS.slice(Math.ceil(m.DEFS.length / 2))} />; })),
  b2h1: dynamic(() => import("@/components/motion/cat/b2").then((m) => function L() { return <MotionShell slug="b2h1" defs={m.DEFS.slice(0, Math.ceil(m.DEFS.length / 2))} />; })),
  b2h2: dynamic(() => import("@/components/motion/cat/b2").then((m) => function L() { return <MotionShell slug="b2h2" defs={m.DEFS.slice(Math.ceil(m.DEFS.length / 2))} />; })),
  b3h1: dynamic(() => import("@/components/motion/cat/b3").then((m) => function L() { return <MotionShell slug="b3h1" defs={m.DEFS.slice(0, Math.ceil(m.DEFS.length / 2))} />; })),
  b3h2: dynamic(() => import("@/components/motion/cat/b3").then((m) => function L() { return <MotionShell slug="b3h2" defs={m.DEFS.slice(Math.ceil(m.DEFS.length / 2))} />; })),
  b4h1: dynamic(() => import("@/components/motion/cat/b4").then((m) => function L() { return <MotionShell slug="b4h1" defs={m.DEFS.slice(0, Math.ceil(m.DEFS.length / 2))} />; })),
  b4h2: dynamic(() => import("@/components/motion/cat/b4").then((m) => function L() { return <MotionShell slug="b4h2" defs={m.DEFS.slice(Math.ceil(m.DEFS.length / 2))} />; })),
  b5h1: dynamic(() => import("@/components/motion/cat/b5").then((m) => function L() { return <MotionShell slug="b5h1" defs={m.DEFS.slice(0, Math.ceil(m.DEFS.length / 2))} />; })),
  b5h2: dynamic(() => import("@/components/motion/cat/b5").then((m) => function L() { return <MotionShell slug="b5h2" defs={m.DEFS.slice(Math.ceil(m.DEFS.length / 2))} />; })),
  b6h1: dynamic(() => import("@/components/motion/cat/b6").then((m) => function L() { return <MotionShell slug="b6h1" defs={m.DEFS.slice(0, Math.ceil(m.DEFS.length / 2))} />; })),
  b6h2: dynamic(() => import("@/components/motion/cat/b6").then((m) => function L() { return <MotionShell slug="b6h2" defs={m.DEFS.slice(Math.ceil(m.DEFS.length / 2))} />; })),
  b7h1: dynamic(() => import("@/components/motion/cat/b7").then((m) => function L() { return <MotionShell slug="b7h1" defs={m.DEFS.slice(0, Math.ceil(m.DEFS.length / 2))} />; })),
  b7h2: dynamic(() => import("@/components/motion/cat/b7").then((m) => function L() { return <MotionShell slug="b7h2" defs={m.DEFS.slice(Math.ceil(m.DEFS.length / 2))} />; })),
  b8h1: dynamic(() => import("@/components/motion/cat/b8").then((m) => function L() { return <MotionShell slug="b8h1" defs={m.DEFS.slice(0, Math.ceil(m.DEFS.length / 2))} />; })),
  b8h2: dynamic(() => import("@/components/motion/cat/b8").then((m) => function L() { return <MotionShell slug="b8h2" defs={m.DEFS.slice(Math.ceil(m.DEFS.length / 2))} />; })),
  b9h1: dynamic(() => import("@/components/motion/cat/b9").then((m) => function L() { return <MotionShell slug="b9h1" defs={m.DEFS.slice(0, Math.ceil(m.DEFS.length / 2))} />; })),
  b9h2: dynamic(() => import("@/components/motion/cat/b9").then((m) => function L() { return <MotionShell slug="b9h2" defs={m.DEFS.slice(Math.ceil(m.DEFS.length / 2))} />; })),
  b10h1: dynamic(() => import("@/components/motion/cat/b10").then((m) => function L() { return <MotionShell slug="b10h1" defs={m.DEFS.slice(0, Math.ceil(m.DEFS.length / 2))} />; })),
  b10h2: dynamic(() => import("@/components/motion/cat/b10").then((m) => function L() { return <MotionShell slug="b10h2" defs={m.DEFS.slice(Math.ceil(m.DEFS.length / 2))} />; })),
  b11h1: dynamic(() => import("@/components/motion/cat/b11").then((m) => function L() { return <MotionShell slug="b11h1" defs={m.DEFS.slice(0, Math.ceil(m.DEFS.length / 2))} />; })),
  b11h2: dynamic(() => import("@/components/motion/cat/b11").then((m) => function L() { return <MotionShell slug="b11h2" defs={m.DEFS.slice(Math.ceil(m.DEFS.length / 2))} />; })),
  b12h1: dynamic(() => import("@/components/motion/cat/b12").then((m) => function L() { return <MotionShell slug="b12h1" defs={m.DEFS.slice(0, Math.ceil(m.DEFS.length / 2))} />; })),
  b12h2: dynamic(() => import("@/components/motion/cat/b12").then((m) => function L() { return <MotionShell slug="b12h2" defs={m.DEFS.slice(Math.ceil(m.DEFS.length / 2))} />; })),
  b13h1: dynamic(() => import("@/components/motion/cat/b13").then((m) => function L() { return <MotionShell slug="b13h1" defs={m.DEFS.slice(0, Math.ceil(m.DEFS.length / 2))} />; })),
  b13h2: dynamic(() => import("@/components/motion/cat/b13").then((m) => function L() { return <MotionShell slug="b13h2" defs={m.DEFS.slice(Math.ceil(m.DEFS.length / 2))} />; })),
};

export default function GroupLab({ slug }: { slug: string }) {
  const P = PAGES[slug];
  return P ? <P /> : null;
}
