"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as AP_B1 } from "../ap-b1";
import { DEFS as AP_B2 } from "../ap-b2";
import { DEFS as AP_B3 } from "../ap-b3";

export const DEFS: SectionDef[] = ([...AP_B1, ...AP_B2, ...AP_B3] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
