"use client";

// All layouts of batch 1 (category order). Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as HR_B1 } from "../hr-b1";
import { DEFS as NV_B1 } from "../nv-b1";
import { DEFS as PS_B1 } from "../ps-b1";
import { DEFS as PD_B1 } from "../pd-b1";
import { DEFS as CP_B1 } from "../cp-b1";
import { DEFS as TM_B1 } from "../tm-b1";
import { DEFS as GL_B1 } from "../gl-b1";
import { DEFS as VD_B1 } from "../vd-b1";
import { DEFS as LG_B1 } from "../lg-b1";
import { DEFS as MN_B1 } from "../mn-b1";
import { DEFS as BK_B1 } from "../bk-b1";
import { DEFS as LS_B1 } from "../ls-b1";
import { DEFS as MP_B1 } from "../mp-b1";
import { DEFS as EV_B1 } from "../ev-b1";
import { DEFS as AP_B1 } from "../ap-b1";
import { DEFS as JR_B1 } from "../jr-b1";
import { DEFS as CC_B1 } from "../cc-b1";
import { DEFS as AN_B1 } from "../an-b1";
import { DEFS as PL_B1 } from "../pl-b1";
import { DEFS as CR_B1 } from "../cr-b1";
import { DEFS as ER_B1 } from "../er-b1";

export const DEFS: SectionDef[] = [...HR_B1, ...NV_B1, ...PS_B1, ...PD_B1, ...CP_B1, ...TM_B1, ...GL_B1, ...VD_B1, ...LG_B1, ...MN_B1, ...BK_B1, ...LS_B1, ...MP_B1, ...EV_B1, ...AP_B1, ...JR_B1, ...CC_B1, ...AN_B1, ...PL_B1, ...CR_B1, ...ER_B1];
