"use client";

// All layouts of batch 2 (category order). Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as HR_B2 } from "../hr-b2";
import { DEFS as NV_B2 } from "../nv-b2";
import { DEFS as FT_B2 } from "../ft-b2";
import { DEFS as BN_B2 } from "../bn-b2";
import { DEFS as PS_B2 } from "../ps-b2";
import { DEFS as ST_B2 } from "../st-b2";
import { DEFS as PD_B2 } from "../pd-b2";
import { DEFS as SY_B2 } from "../sy-b2";
import { DEFS as TM_B2 } from "../tm-b2";
import { DEFS as GL_B2 } from "../gl-b2";
import { DEFS as VD_B2 } from "../vd-b2";
import { DEFS as SP_B2 } from "../sp-b2";
import { DEFS as LG_B2 } from "../lg-b2";
import { DEFS as PR_B2 } from "../pr-b2";
import { DEFS as MN_B2 } from "../mn-b2";
import { DEFS as BK_B2 } from "../bk-b2";
import { DEFS as LS_B2 } from "../ls-b2";
import { DEFS as MP_B2 } from "../mp-b2";
import { DEFS as EV_B2 } from "../ev-b2";
import { DEFS as AP_B2 } from "../ap-b2";
import { DEFS as JR_B2 } from "../jr-b2";
import { DEFS as FQ_B2 } from "../fq-b2";
import { DEFS as CT_B2 } from "../ct-b2";
import { DEFS as CC_B2 } from "../cc-b2";
import { DEFS as FO_B2 } from "../fo-b2";

export const DEFS: SectionDef[] = [...HR_B2, ...NV_B2, ...FT_B2, ...BN_B2, ...PS_B2, ...ST_B2, ...PD_B2, ...SY_B2, ...TM_B2, ...GL_B2, ...VD_B2, ...SP_B2, ...LG_B2, ...PR_B2, ...MN_B2, ...BK_B2, ...LS_B2, ...MP_B2, ...EV_B2, ...AP_B2, ...JR_B2, ...FQ_B2, ...CT_B2, ...CC_B2, ...FO_B2];
