"use client";

// All layouts of batch 3 (category order). Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as HR_B3 } from "../hr-b3";
import { DEFS as NV_B3 } from "../nv-b3";
import { DEFS as FT_B3 } from "../ft-b3";
import { DEFS as BN_B3 } from "../bn-b3";
import { DEFS as PS_B3 } from "../ps-b3";
import { DEFS as ST_B3 } from "../st-b3";
import { DEFS as PD_B3 } from "../pd-b3";
import { DEFS as CP_B3 } from "../cp-b3";
import { DEFS as SY_B3 } from "../sy-b3";
import { DEFS as TM_B3 } from "../tm-b3";
import { DEFS as GL_B3 } from "../gl-b3";
import { DEFS as VD_B3 } from "../vd-b3";
import { DEFS as SP_B3 } from "../sp-b3";
import { DEFS as LG_B3 } from "../lg-b3";
import { DEFS as PR_B3 } from "../pr-b3";
import { DEFS as MN_B3 } from "../mn-b3";
import { DEFS as BK_B3 } from "../bk-b3";
import { DEFS as MP_B3 } from "../mp-b3";
import { DEFS as EV_B3 } from "../ev-b3";
import { DEFS as AP_B3 } from "../ap-b3";
import { DEFS as JR_B3 } from "../jr-b3";
import { DEFS as FQ_B3 } from "../fq-b3";
import { DEFS as CT_B3 } from "../ct-b3";
import { DEFS as CC_B3 } from "../cc-b3";
import { DEFS as FO_B3 } from "../fo-b3";

export const DEFS: SectionDef[] = [...HR_B3, ...NV_B3, ...FT_B3, ...BN_B3, ...PS_B3, ...ST_B3, ...PD_B3, ...CP_B3, ...SY_B3, ...TM_B3, ...GL_B3, ...VD_B3, ...SP_B3, ...LG_B3, ...PR_B3, ...MN_B3, ...BK_B3, ...MP_B3, ...EV_B3, ...AP_B3, ...JR_B3, ...FQ_B3, ...CT_B3, ...CC_B3, ...FO_B3];
