"use client";

// All layouts of batch 4 (category order). Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as HR_B4 } from "../hr-b4";
import { DEFS as NV_B4 } from "../nv-b4";
import { DEFS as FT_B4 } from "../ft-b4";
import { DEFS as PS_B4 } from "../ps-b4";
import { DEFS as ST_B4 } from "../st-b4";
import { DEFS as PD_B4 } from "../pd-b4";
import { DEFS as SY_B4 } from "../sy-b4";
import { DEFS as TM_B4 } from "../tm-b4";
import { DEFS as GL_B4 } from "../gl-b4";
import { DEFS as VD_B4 } from "../vd-b4";
import { DEFS as SP_B4 } from "../sp-b4";
import { DEFS as LG_B4 } from "../lg-b4";
import { DEFS as PR_B4 } from "../pr-b4";
import { DEFS as MN_B4 } from "../mn-b4";
import { DEFS as BK_B4 } from "../bk-b4";
import { DEFS as LS_B4 } from "../ls-b4";
import { DEFS as MP_B4 } from "../mp-b4";
import { DEFS as EV_B4 } from "../ev-b4";
import { DEFS as JR_B4 } from "../jr-b4";
import { DEFS as FQ_B4 } from "../fq-b4";
import { DEFS as CT_B4 } from "../ct-b4";
import { DEFS as NL_B4 } from "../nl-b4";
import { DEFS as CC_B4 } from "../cc-b4";
import { DEFS as FO_B4 } from "../fo-b4";

export const DEFS: SectionDef[] = [...HR_B4, ...NV_B4, ...FT_B4, ...PS_B4, ...ST_B4, ...PD_B4, ...SY_B4, ...TM_B4, ...GL_B4, ...VD_B4, ...SP_B4, ...LG_B4, ...PR_B4, ...MN_B4, ...BK_B4, ...LS_B4, ...MP_B4, ...EV_B4, ...JR_B4, ...FQ_B4, ...CT_B4, ...NL_B4, ...CC_B4, ...FO_B4];
