"use client";

// All layouts of batch 5 (category order). Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as HR_B5 } from "../hr-b5";
import { DEFS as NV_B5 } from "../nv-b5";
import { DEFS as FT_B5 } from "../ft-b5";
import { DEFS as BN_B5 } from "../bn-b5";
import { DEFS as PS_B5 } from "../ps-b5";
import { DEFS as ST_B5 } from "../st-b5";
import { DEFS as PD_B5 } from "../pd-b5";
import { DEFS as CP_B5 } from "../cp-b5";
import { DEFS as SY_B5 } from "../sy-b5";
import { DEFS as TM_B5 } from "../tm-b5";
import { DEFS as GL_B5 } from "../gl-b5";
import { DEFS as VD_B5 } from "../vd-b5";
import { DEFS as SP_B5 } from "../sp-b5";
import { DEFS as LG_B5 } from "../lg-b5";
import { DEFS as PR_B5 } from "../pr-b5";
import { DEFS as MN_B5 } from "../mn-b5";
import { DEFS as BK_B5 } from "../bk-b5";
import { DEFS as MP_B5 } from "../mp-b5";
import { DEFS as EV_B5 } from "../ev-b5";
import { DEFS as AP_B5 } from "../ap-b5";
import { DEFS as JR_B5 } from "../jr-b5";
import { DEFS as FQ_B5 } from "../fq-b5";
import { DEFS as CT_B5 } from "../ct-b5";
import { DEFS as CC_B5 } from "../cc-b5";
import { DEFS as FO_B5 } from "../fo-b5";

export const DEFS: SectionDef[] = [...HR_B5, ...NV_B5, ...FT_B5, ...BN_B5, ...PS_B5, ...ST_B5, ...PD_B5, ...CP_B5, ...SY_B5, ...TM_B5, ...GL_B5, ...VD_B5, ...SP_B5, ...LG_B5, ...PR_B5, ...MN_B5, ...BK_B5, ...MP_B5, ...EV_B5, ...AP_B5, ...JR_B5, ...FQ_B5, ...CT_B5, ...CC_B5, ...FO_B5];
