"use client";

// All layouts of batch 6 (category order). Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as HR_B6 } from "../hr-b6";
import { DEFS as NV_B6 } from "../nv-b6";
import { DEFS as FT_B6 } from "../ft-b6";
import { DEFS as BN_B6 } from "../bn-b6";
import { DEFS as PS_B6 } from "../ps-b6";
import { DEFS as ST_B6 } from "../st-b6";
import { DEFS as PD_B6 } from "../pd-b6";
import { DEFS as SY_B6 } from "../sy-b6";
import { DEFS as TM_B6 } from "../tm-b6";
import { DEFS as GL_B6 } from "../gl-b6";
import { DEFS as VD_B6 } from "../vd-b6";
import { DEFS as SP_B6 } from "../sp-b6";
import { DEFS as LG_B6 } from "../lg-b6";
import { DEFS as PR_B6 } from "../pr-b6";
import { DEFS as MN_B6 } from "../mn-b6";
import { DEFS as BK_B6 } from "../bk-b6";
import { DEFS as LS_B6 } from "../ls-b6";
import { DEFS as MP_B6 } from "../mp-b6";
import { DEFS as EV_B6 } from "../ev-b6";
import { DEFS as AP_B6 } from "../ap-b6";
import { DEFS as JR_B6 } from "../jr-b6";
import { DEFS as FQ_B6 } from "../fq-b6";
import { DEFS as CT_B6 } from "../ct-b6";
import { DEFS as CC_B6 } from "../cc-b6";
import { DEFS as FO_B6 } from "../fo-b6";

export const DEFS: SectionDef[] = [...HR_B6, ...NV_B6, ...FT_B6, ...BN_B6, ...PS_B6, ...ST_B6, ...PD_B6, ...SY_B6, ...TM_B6, ...GL_B6, ...VD_B6, ...SP_B6, ...LG_B6, ...PR_B6, ...MN_B6, ...BK_B6, ...LS_B6, ...MP_B6, ...EV_B6, ...AP_B6, ...JR_B6, ...FQ_B6, ...CT_B6, ...CC_B6, ...FO_B6];
