"use client";

// All layouts of batch 7 (category order). Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as HR_B7 } from "../hr-b7";
import { DEFS as NV_B7 } from "../nv-b7";
import { DEFS as FT_B7 } from "../ft-b7";
import { DEFS as PS_B7 } from "../ps-b7";
import { DEFS as ST_B7 } from "../st-b7";
import { DEFS as SY_B7 } from "../sy-b7";
import { DEFS as TM_B7 } from "../tm-b7";
import { DEFS as GL_B7 } from "../gl-b7";
import { DEFS as VD_B7 } from "../vd-b7";
import { DEFS as SP_B7 } from "../sp-b7";
import { DEFS as LG_B7 } from "../lg-b7";
import { DEFS as PR_B7 } from "../pr-b7";
import { DEFS as MP_B7 } from "../mp-b7";
import { DEFS as JR_B7 } from "../jr-b7";
import { DEFS as FQ_B7 } from "../fq-b7";
import { DEFS as CC_B7 } from "../cc-b7";

export const DEFS: SectionDef[] = [...HR_B7, ...NV_B7, ...FT_B7, ...PS_B7, ...ST_B7, ...SY_B7, ...TM_B7, ...GL_B7, ...VD_B7, ...SP_B7, ...LG_B7, ...PR_B7, ...MP_B7, ...JR_B7, ...FQ_B7, ...CC_B7];
