"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as BK_B1 } from "../bk-b1";

export const DEFS: SectionDef[] = ([...BK_B1] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
