"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { BENTO } from "../bento";
import { DEFS as BN_B2 } from "../bn-b2";

export const DEFS: SectionDef[] = ([...BENTO, ...BN_B2] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
