"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { BENTO } from "../bento";
import { DEFS as BN_B2 } from "../bn-b2";
import { DEFS as BN_B3 } from "../bn-b3";
import { DEFS as BN_B5 } from "../bn-b5";
import { DEFS as BN_B6 } from "../bn-b6";

export const DEFS: SectionDef[] = ([...BENTO, ...BN_B2, ...BN_B3, ...BN_B5, ...BN_B6] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
