"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as CC_B1 } from "../cc-b1";
import { DEFS as CC_B2 } from "../cc-b2";

export const DEFS: SectionDef[] = ([...CC_B1, ...CC_B2] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
