"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { CTA } from "../cta";
import { DEFS as CT_B2 } from "../ct-b2";
import { DEFS as CT_B3 } from "../ct-b3";
import { DEFS as CT_B4 } from "../ct-b4";
import { DEFS as CT_B5 } from "../ct-b5";
import { DEFS as CT_B6 } from "../ct-b6";

export const DEFS: SectionDef[] = ([...CTA, ...CT_B2, ...CT_B3, ...CT_B4, ...CT_B5, ...CT_B6] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
