"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { CTA } from "../cta";
import { DEFS as CT_B2 } from "../ct-b2";

export const DEFS: SectionDef[] = ([...CTA, ...CT_B2] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
