"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as EV_B1 } from "../ev-b1";
import { DEFS as EV_B2 } from "../ev-b2";
import { DEFS as EV_B3 } from "../ev-b3";

export const DEFS: SectionDef[] = ([...EV_B1, ...EV_B2, ...EV_B3] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
