"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as EV_B1 } from "../ev-b1";
import { DEFS as EV_B2 } from "../ev-b2";
import { DEFS as EV_B3 } from "../ev-b3";
import { DEFS as EV_B4 } from "../ev-b4";
import { DEFS as EV_B5 } from "../ev-b5";
import { DEFS as EV_B6 } from "../ev-b6";

export const DEFS: SectionDef[] = ([...EV_B1, ...EV_B2, ...EV_B3, ...EV_B4, ...EV_B5, ...EV_B6] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
