"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { FAQ } from "../faq";
import { DEFS as FQ_B2 } from "../fq-b2";

export const DEFS: SectionDef[] = ([...FAQ, ...FQ_B2] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
