"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { FEATURES } from "../features";
import { DEFS as FT_B2 } from "../ft-b2";
import { DEFS as FT_B3 } from "../ft-b3";

export const DEFS: SectionDef[] = ([...FEATURES, ...FT_B2, ...FT_B3] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
