"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { FEATURES } from "../features";
import { DEFS as FT_B2 } from "../ft-b2";
import { DEFS as FT_B3 } from "../ft-b3";
import { DEFS as FT_B4 } from "../ft-b4";
import { DEFS as FT_B5 } from "../ft-b5";
import { DEFS as FT_B6 } from "../ft-b6";

export const DEFS: SectionDef[] = ([...FEATURES, ...FT_B2, ...FT_B3, ...FT_B4, ...FT_B5, ...FT_B6] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
