"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { GALLERY } from "../gallery";
import { DEFS as GL_B1 } from "../gl-b1";

export const DEFS: SectionDef[] = ([...GALLERY, ...GL_B1] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
