"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { GALLERY } from "../gallery";
import { DEFS as GL_B1 } from "../gl-b1";
import { DEFS as GL_B2 } from "../gl-b2";
import { DEFS as GL_B3 } from "../gl-b3";
import { DEFS as GL_B4 } from "../gl-b4";
import { DEFS as GL_B5 } from "../gl-b5";
import { DEFS as GL_B6 } from "../gl-b6";
import { DEFS as GL_B7 } from "../gl-b7";

export const DEFS: SectionDef[] = ([...GALLERY, ...GL_B1, ...GL_B2, ...GL_B3, ...GL_B4, ...GL_B5, ...GL_B6, ...GL_B7] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
