"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as JR_B1 } from "../jr-b1";
import { DEFS as JR_B2 } from "../jr-b2";

export const DEFS: SectionDef[] = ([...JR_B1, ...JR_B2] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
