"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as JR_B1 } from "../jr-b1";
import { DEFS as JR_B2 } from "../jr-b2";
import { DEFS as JR_B3 } from "../jr-b3";
import { DEFS as JR_B4 } from "../jr-b4";

export const DEFS: SectionDef[] = ([...JR_B1, ...JR_B2, ...JR_B3, ...JR_B4] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
