"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as LG_B1 } from "../lg-b1";
import { DEFS as LG_B2 } from "../lg-b2";
import { DEFS as LG_B3 } from "../lg-b3";
import { DEFS as LG_B4 } from "../lg-b4";

export const DEFS: SectionDef[] = ([...LG_B1, ...LG_B2, ...LG_B3, ...LG_B4] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
