"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as LS_B1 } from "../ls-b1";
import { DEFS as LS_B2 } from "../ls-b2";
import { DEFS as LS_B4 } from "../ls-b4";
import { DEFS as LS_B6 } from "../ls-b6";

export const DEFS: SectionDef[] = ([...LS_B1, ...LS_B2, ...LS_B4, ...LS_B6] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
