"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as MN_B1 } from "../mn-b1";
import { DEFS as MN_B2 } from "../mn-b2";
import { DEFS as MN_B3 } from "../mn-b3";
import { DEFS as MN_B4 } from "../mn-b4";

export const DEFS: SectionDef[] = ([...MN_B1, ...MN_B2, ...MN_B3, ...MN_B4] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
