"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as MP_B1 } from "../mp-b1";
import { DEFS as MP_B2 } from "../mp-b2";
import { DEFS as MP_B3 } from "../mp-b3";
import { DEFS as MP_B4 } from "../mp-b4";
import { DEFS as MP_B5 } from "../mp-b5";
import { DEFS as MP_B6 } from "../mp-b6";
import { DEFS as MP_B7 } from "../mp-b7";

export const DEFS: SectionDef[] = ([...MP_B1, ...MP_B2, ...MP_B3, ...MP_B4, ...MP_B5, ...MP_B6, ...MP_B7] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
