"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as MP_B1 } from "../mp-b1";
import { DEFS as MP_B2 } from "../mp-b2";
import { DEFS as MP_B3 } from "../mp-b3";

export const DEFS: SectionDef[] = ([...MP_B1, ...MP_B2, ...MP_B3] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
