"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { NEWSLETTER } from "../newsletter";
import { DEFS as NL_B4 } from "../nl-b4";

export const DEFS: SectionDef[] = ([...NEWSLETTER, ...NL_B4] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
