"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as NV_B1 } from "../nv-b1";
import { DEFS as NV_B2 } from "../nv-b2";

export const DEFS: SectionDef[] = ([...NV_B1, ...NV_B2] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
