"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as PD_B1 } from "../pd-b1";
import { DEFS as PD_B2 } from "../pd-b2";
import { DEFS as PD_B3 } from "../pd-b3";
import { DEFS as PD_B4 } from "../pd-b4";
import { DEFS as PD_B5 } from "../pd-b5";

export const DEFS: SectionDef[] = ([...PD_B1, ...PD_B2, ...PD_B3, ...PD_B4, ...PD_B5] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
