"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as PD_B1 } from "../pd-b1";
import { DEFS as PD_B2 } from "../pd-b2";

export const DEFS: SectionDef[] = ([...PD_B1, ...PD_B2] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
