"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { PRICING } from "../pricing";
import { DEFS as PR_B2 } from "../pr-b2";
import { DEFS as PR_B3 } from "../pr-b3";
import { DEFS as PR_B4 } from "../pr-b4";
import { DEFS as PR_B5 } from "../pr-b5";
import { DEFS as PR_B6 } from "../pr-b6";
import { DEFS as PR_B7 } from "../pr-b7";

export const DEFS: SectionDef[] = ([...PRICING, ...PR_B2, ...PR_B3, ...PR_B4, ...PR_B5, ...PR_B6, ...PR_B7] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
