"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { PRICING } from "../pricing";
import { DEFS as PR_B2 } from "../pr-b2";
import { DEFS as PR_B3 } from "../pr-b3";

export const DEFS: SectionDef[] = ([...PRICING, ...PR_B2, ...PR_B3] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
