"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { PRODUCT } from "../product";
import { DEFS as PS_B1 } from "../ps-b1";

export const DEFS: SectionDef[] = ([...PRODUCT, ...PS_B1] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
