"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { PROOF } from "../proof";
import { DEFS as SP_B2 } from "../sp-b2";
import { DEFS as SP_B3 } from "../sp-b3";

export const DEFS: SectionDef[] = ([...PROOF, ...SP_B2, ...SP_B3] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
