"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { PROOF } from "../proof";

export const DEFS: SectionDef[] = ([...PROOF] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
