"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { STATS } from "../stats";
import { DEFS as ST_B2 } from "../st-b2";
import { DEFS as ST_B3 } from "../st-b3";

export const DEFS: SectionDef[] = ([...STATS, ...ST_B2, ...ST_B3] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
