"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { STORY } from "../story";
import { DEFS as SY_B2 } from "../sy-b2";
import { DEFS as SY_B3 } from "../sy-b3";
import { DEFS as SY_B4 } from "../sy-b4";
import { DEFS as SY_B5 } from "../sy-b5";
import { DEFS as SY_B6 } from "../sy-b6";

export const DEFS: SectionDef[] = ([...STORY, ...SY_B2, ...SY_B3, ...SY_B4, ...SY_B5, ...SY_B6] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
