"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { STORY } from "../story";
import { DEFS as SY_B2 } from "../sy-b2";

export const DEFS: SectionDef[] = ([...STORY, ...SY_B2] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
