"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as TM_B1 } from "../tm-b1";
import { DEFS as TM_B2 } from "../tm-b2";
import { DEFS as TM_B3 } from "../tm-b3";
import { DEFS as TM_B4 } from "../tm-b4";
import { DEFS as TM_B5 } from "../tm-b5";
import { DEFS as TM_B6 } from "../tm-b6";
import { DEFS as TM_B7 } from "../tm-b7";

export const DEFS: SectionDef[] = ([...TM_B1, ...TM_B2, ...TM_B3, ...TM_B4, ...TM_B5, ...TM_B6, ...TM_B7] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
