"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as TM_B1 } from "../tm-b1";
import { DEFS as TM_B2 } from "../tm-b2";

export const DEFS: SectionDef[] = ([...TM_B1, ...TM_B2] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
