"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as VD_B1 } from "../vd-b1";
import { DEFS as VD_B2 } from "../vd-b2";
import { DEFS as VD_B3 } from "../vd-b3";
import { DEFS as VD_B4 } from "../vd-b4";
import { DEFS as VD_B5 } from "../vd-b5";
import { DEFS as VD_B6 } from "../vd-b6";

export const DEFS: SectionDef[] = ([...VD_B1, ...VD_B2, ...VD_B3, ...VD_B4, ...VD_B5, ...VD_B6] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
