"use client";

// All layouts of this SECTION-MENU category, in code order. Generated by scripts/section-cats.mjs — do not edit.
import type { SectionDef } from "../types";
import { DEFS as VD_B1 } from "../vd-b1";
import { DEFS as VD_B2 } from "../vd-b2";

export const DEFS: SectionDef[] = ([...VD_B1, ...VD_B2] as SectionDef[]).sort((a, b) => a.code.localeCompare(b.code));
