"use client";

// All motions of the "ambient" group, in code order. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as AMBIENT_B2_4 } from "../ambient-b2-4";
import { DEFS as AMBIENT_B2_5 } from "../ambient-b2-5";
import { DEFS as AMBIENT_B3_1 } from "../ambient-b3-1";
import { DEFS as AMBIENT_B3_2 } from "../ambient-b3-2";
import { DEFS as AMBIENT_B11_3 } from "../ambient-b11-3";
import { DEFS as AMBIENT_B11_4 } from "../ambient-b11-4";
import { DEFS as AMBIENT_B11_5 } from "../ambient-b11-5";

export const DEFS: MotionDef[] = ([...AMBIENT_B2_4, ...AMBIENT_B2_5, ...AMBIENT_B3_1, ...AMBIENT_B3_2, ...AMBIENT_B11_3, ...AMBIENT_B11_4, ...AMBIENT_B11_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
