"use client";

// All motions of batch 1. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as REVEAL_B1_1 } from "../reveal-b1-1";
import { DEFS as REVEAL_B1_2 } from "../reveal-b1-2";
import { DEFS as TEXT_B1_2 } from "../text-b1-2";
import { DEFS as TEXT_B1_3 } from "../text-b1-3";
import { DEFS as TEXT_B1_4 } from "../text-b1-4";
import { DEFS as TEXT_B1_5 } from "../text-b1-5";

export const DEFS: MotionDef[] = ([...REVEAL_B1_1, ...REVEAL_B1_2, ...TEXT_B1_2, ...TEXT_B1_3, ...TEXT_B1_4, ...TEXT_B1_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
