"use client";

// All motions of batch 10. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as SCROLL_B10_1 } from "../scroll-b10-1";
import { DEFS as IMAGE_B10_1 } from "../image-b10-1";
import { DEFS as IMAGE_B10_2 } from "../image-b10-2";
import { DEFS as IMAGE_B10_3 } from "../image-b10-3";
import { DEFS as IMAGE_B10_4 } from "../image-b10-4";
import { DEFS as IMAGE_B10_5 } from "../image-b10-5";

export const DEFS: MotionDef[] = ([...SCROLL_B10_1, ...IMAGE_B10_1, ...IMAGE_B10_2, ...IMAGE_B10_3, ...IMAGE_B10_4, ...IMAGE_B10_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
