"use client";

// All motions of batch 11. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as IMAGE_B11_1 } from "../image-b11-1";
import { DEFS as IMAGE_B11_2 } from "../image-b11-2";
import { DEFS as IMAGE_B11_3 } from "../image-b11-3";
import { DEFS as AMBIENT_B11_3 } from "../ambient-b11-3";
import { DEFS as AMBIENT_B11_4 } from "../ambient-b11-4";
import { DEFS as AMBIENT_B11_5 } from "../ambient-b11-5";

export const DEFS: MotionDef[] = ([...IMAGE_B11_1, ...IMAGE_B11_2, ...IMAGE_B11_3, ...AMBIENT_B11_3, ...AMBIENT_B11_4, ...AMBIENT_B11_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
