"use client";

// All motions of batch 12. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as AMBIENT_B12_1 } from "../ambient-b12-1";
import { DEFS as AMBIENT_B12_2 } from "../ambient-b12-2";
import { DEFS as AMBIENT_B12_3 } from "../ambient-b12-3";
import { DEFS as AMBIENT_B12_4 } from "../ambient-b12-4";
import { DEFS as AMBIENT_B12_5 } from "../ambient-b12-5";

export const DEFS: MotionDef[] = ([...AMBIENT_B12_1, ...AMBIENT_B12_2, ...AMBIENT_B12_3, ...AMBIENT_B12_4, ...AMBIENT_B12_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
