"use client";

// All motions of batch 13. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as AMBIENT_B13_1 } from "../ambient-b13-1";
import { DEFS as AMBIENT_B13_2 } from "../ambient-b13-2";
import { DEFS as TRANSITION_B13_2 } from "../transition-b13-2";
import { DEFS as TRANSITION_B13_3 } from "../transition-b13-3";
import { DEFS as TRANSITION_B13_4 } from "../transition-b13-4";
import { DEFS as TRANSITION_B13_5 } from "../transition-b13-5";

export const DEFS: MotionDef[] = ([...AMBIENT_B13_1, ...AMBIENT_B13_2, ...TRANSITION_B13_2, ...TRANSITION_B13_3, ...TRANSITION_B13_4, ...TRANSITION_B13_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
