"use client";

// All motions of batch 14. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as TRANSITION_B14_1 } from "../transition-b14-1";
import { DEFS as TRANSITION_B14_2 } from "../transition-b14-2";
import { DEFS as LOADER_B14_1 } from "../loader-b14-1";
import { DEFS as MICRO_B14_2 } from "../micro-b14-2";
import { DEFS as MICRO_B14_3 } from "../micro-b14-3";
import { DEFS as MICRO_B14_4 } from "../micro-b14-4";
import { DEFS as MICRO_B14_5 } from "../micro-b14-5";

export const DEFS: MotionDef[] = ([...TRANSITION_B14_1, ...TRANSITION_B14_2, ...LOADER_B14_1, ...MICRO_B14_2, ...MICRO_B14_3, ...MICRO_B14_4, ...MICRO_B14_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
