"use client";

// All motions of batch 15. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as REVEAL_B15_1 } from "../reveal-b15-1";
import { DEFS as REVEAL_B15_2 } from "../reveal-b15-2";
import { DEFS as TEXT_B15_2 } from "../text-b15-2";
import { DEFS as TEXT_B15_3 } from "../text-b15-3";
import { DEFS as TEXT_B15_4 } from "../text-b15-4";
import { DEFS as SCROLL_B15_4 } from "../scroll-b15-4";
import { DEFS as SCROLL_B15_5 } from "../scroll-b15-5";
import { DEFS as IMAGE_B15_5 } from "../image-b15-5";
import { DEFS as MICRO_B15_1 } from "../micro-b15-1";

export const DEFS: MotionDef[] = ([...REVEAL_B15_1, ...REVEAL_B15_2, ...TEXT_B15_2, ...TEXT_B15_3, ...TEXT_B15_4, ...SCROLL_B15_4, ...SCROLL_B15_5, ...IMAGE_B15_5, ...MICRO_B15_1] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
