"use client";

// All motions of batch 16. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as IMAGE_B16_1 } from "../image-b16-1";
import { DEFS as AMBIENT_B16_1 } from "../ambient-b16-1";
import { DEFS as AMBIENT_B16_2 } from "../ambient-b16-2";
import { DEFS as AMBIENT_B16_3 } from "../ambient-b16-3";
import { DEFS as AMBIENT_B16_4 } from "../ambient-b16-4";
import { DEFS as AMBIENT_B16_5 } from "../ambient-b16-5";

export const DEFS: MotionDef[] = ([...IMAGE_B16_1, ...AMBIENT_B16_1, ...AMBIENT_B16_2, ...AMBIENT_B16_3, ...AMBIENT_B16_4, ...AMBIENT_B16_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
