"use client";

// All motions of batch 17. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as AMBIENT_B17_1 } from "../ambient-b17-1";
import { DEFS as AMBIENT_B17_2 } from "../ambient-b17-2";
import { DEFS as TRANSITION_B17_2 } from "../transition-b17-2";
import { DEFS as TRANSITION_B17_3 } from "../transition-b17-3";
import { DEFS as LOADER_B17_3 } from "../loader-b17-3";
import { DEFS as LOADER_B17_4 } from "../loader-b17-4";
import { DEFS as LOADER_B17_5 } from "../loader-b17-5";
import { DEFS as MICRO_B17_5 } from "../micro-b17-5";

export const DEFS: MotionDef[] = ([...AMBIENT_B17_1, ...AMBIENT_B17_2, ...TRANSITION_B17_2, ...TRANSITION_B17_3, ...LOADER_B17_3, ...LOADER_B17_4, ...LOADER_B17_5, ...MICRO_B17_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
