"use client";

// All motions of batch 18. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as MICRO_B18_1 } from "../micro-b18-1";
import { DEFS as MICRO_B18_2 } from "../micro-b18-2";
import { DEFS as MICRO_B18_3 } from "../micro-b18-3";
import { DEFS as MICRO_B18_4 } from "../micro-b18-4";
import { DEFS as MICRO_B18_5 } from "../micro-b18-5";

export const DEFS: MotionDef[] = ([...MICRO_B18_1, ...MICRO_B18_2, ...MICRO_B18_3, ...MICRO_B18_4, ...MICRO_B18_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
