"use client";

// All motions of batch 19. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as MICRO_B19_1 } from "../micro-b19-1";
import { DEFS as MICRO_B19_2 } from "../micro-b19-2";
import { DEFS as MICRO_B19_3 } from "../micro-b19-3";
import { DEFS as MICRO_B19_4 } from "../micro-b19-4";

export const DEFS: MotionDef[] = ([...MICRO_B19_1, ...MICRO_B19_2, ...MICRO_B19_3, ...MICRO_B19_4] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
