"use client";

// All motions of batch 2. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as TEXT_B2_1 } from "../text-b2-1";
import { DEFS as SCROLL_B2_1 } from "../scroll-b2-1";
import { DEFS as SCROLL_B2_2 } from "../scroll-b2-2";
import { DEFS as SCROLL_B2_3 } from "../scroll-b2-3";
import { DEFS as IMAGE_B2_3 } from "../image-b2-3";
import { DEFS as IMAGE_B2_4 } from "../image-b2-4";
import { DEFS as AMBIENT_B2_4 } from "../ambient-b2-4";
import { DEFS as AMBIENT_B2_5 } from "../ambient-b2-5";

export const DEFS: MotionDef[] = ([...TEXT_B2_1, ...SCROLL_B2_1, ...SCROLL_B2_2, ...SCROLL_B2_3, ...IMAGE_B2_3, ...IMAGE_B2_4, ...AMBIENT_B2_4, ...AMBIENT_B2_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
