"use client";

// All motions of batch 3. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as AMBIENT_B3_1 } from "../ambient-b3-1";
import { DEFS as AMBIENT_B3_2 } from "../ambient-b3-2";
import { DEFS as TRANSITION_B3_2 } from "../transition-b3-2";
import { DEFS as TRANSITION_B3_3 } from "../transition-b3-3";
import { DEFS as TRANSITION_B3_4 } from "../transition-b3-4";
import { DEFS as LOADER_B3_4 } from "../loader-b3-4";
import { DEFS as LOADER_B3_5 } from "../loader-b3-5";
import { DEFS as MICRO_B3_5 } from "../micro-b3-5";

export const DEFS: MotionDef[] = ([...AMBIENT_B3_1, ...AMBIENT_B3_2, ...TRANSITION_B3_2, ...TRANSITION_B3_3, ...TRANSITION_B3_4, ...LOADER_B3_4, ...LOADER_B3_5, ...MICRO_B3_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
