"use client";

// All motions of batch 4. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as MICRO_B4_1 } from "../micro-b4-1";
import { DEFS as MICRO_B4_2 } from "../micro-b4-2";
import { DEFS as MICRO_B4_3 } from "../micro-b4-3";
import { DEFS as MICRO_B4_4 } from "../micro-b4-4";
import { DEFS as MICRO_B4_5 } from "../micro-b4-5";

export const DEFS: MotionDef[] = ([...MICRO_B4_1, ...MICRO_B4_2, ...MICRO_B4_3, ...MICRO_B4_4, ...MICRO_B4_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
