"use client";

// All motions of batch 5. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as REVEAL_B5_1 } from "../reveal-b5-1";
import { DEFS as REVEAL_B5_2 } from "../reveal-b5-2";
import { DEFS as MICRO_B5_2 } from "../micro-b5-2";
import { DEFS as MICRO_B5_3 } from "../micro-b5-3";
import { DEFS as MICRO_B5_4 } from "../micro-b5-4";
import { DEFS as MICRO_B5_5 } from "../micro-b5-5";

export const DEFS: MotionDef[] = ([...REVEAL_B5_1, ...REVEAL_B5_2, ...MICRO_B5_2, ...MICRO_B5_3, ...MICRO_B5_4, ...MICRO_B5_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
