"use client";

// All motions of batch 6. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as REVEAL_B6_1 } from "../reveal-b6-1";
import { DEFS as REVEAL_B6_2 } from "../reveal-b6-2";
import { DEFS as REVEAL_B6_3 } from "../reveal-b6-3";
import { DEFS as TEXT_B6_3 } from "../text-b6-3";
import { DEFS as TEXT_B6_4 } from "../text-b6-4";
import { DEFS as TEXT_B6_5 } from "../text-b6-5";

export const DEFS: MotionDef[] = ([...REVEAL_B6_1, ...REVEAL_B6_2, ...REVEAL_B6_3, ...TEXT_B6_3, ...TEXT_B6_4, ...TEXT_B6_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
