"use client";

// All motions of batch 8. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as TEXT_B8_1 } from "../text-b8-1";
import { DEFS as TEXT_B8_2 } from "../text-b8-2";
import { DEFS as TEXT_B8_3 } from "../text-b8-3";
import { DEFS as TEXT_B8_4 } from "../text-b8-4";
import { DEFS as TEXT_B8_5 } from "../text-b8-5";
import { DEFS as SCROLL_B8_5 } from "../scroll-b8-5";

export const DEFS: MotionDef[] = ([...TEXT_B8_1, ...TEXT_B8_2, ...TEXT_B8_3, ...TEXT_B8_4, ...TEXT_B8_5, ...SCROLL_B8_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
