"use client";

// All motions of the "image" group, in code order. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as IMAGE_B2_3 } from "../image-b2-3";
import { DEFS as IMAGE_B2_4 } from "../image-b2-4";

export const DEFS: MotionDef[] = ([...IMAGE_B2_3, ...IMAGE_B2_4] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
