"use client";

// All motions of the "loader" group, in code order. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as LOADER_B3_4 } from "../loader-b3-4";
import { DEFS as LOADER_B3_5 } from "../loader-b3-5";
import { DEFS as LOADER_B14_1 } from "../loader-b14-1";

export const DEFS: MotionDef[] = ([...LOADER_B3_4, ...LOADER_B3_5, ...LOADER_B14_1] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
