"use client";

// All motions of the "micro" group, in code order. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as MICRO_B3_5 } from "../micro-b3-5";

export const DEFS: MotionDef[] = ([...MICRO_B3_5] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
