"use client";

// All motions of the "reveal" group, in code order. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as REVEAL_B1_1 } from "../reveal-b1-1";
import { DEFS as REVEAL_B1_2 } from "../reveal-b1-2";

export const DEFS: MotionDef[] = ([...REVEAL_B1_1, ...REVEAL_B1_2] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
