"use client";

// All motions of the "scroll" group, in code order. Generated by scripts/motion-cats.mjs — do not edit.
import type { MotionDef } from "../types";
import { DEFS as SCROLL_B2_1 } from "../scroll-b2-1";
import { DEFS as SCROLL_B2_2 } from "../scroll-b2-2";
import { DEFS as SCROLL_B2_3 } from "../scroll-b2-3";

export const DEFS: MotionDef[] = ([...SCROLL_B2_1, ...SCROLL_B2_2, ...SCROLL_B2_3] as MotionDef[]).sort((a, b) => a.code[0].localeCompare(b.code[0]) || parseInt(a.code.slice(1)) - parseInt(b.code.slice(1)));
